### ISSUE TITLE
Assets in theme.yml is not working

### ISSUE THREAD

**Issue by andreacasali** [PrestaShop/StarterTheme#181]
Hi,

reading the doc (http://developers.prestashop.com/themes/assets/index.html) I found that i can add js/css file for specific templates editing the theme.yml file, simply adding (just for example):

```
assets:
  css:
    all:
      - id: bootstrap-style
        path: assets/css/bootstrap.min.css
  js:
    product:
      - id: jquery
        path: assets/js/jquery.min.js
        priority: 200
        position: bottom
```

but it doesn't work. What am I doing wrong?

**Comment by kpodemski** [comment]
@andreacasali it is working but you need to delete config/themes/themename/shop1.json file to reload updated .yml file in your back-office, it is fixed in 1.7.1 but not working as expected on 1.7.0.x

**Comment by andreacasali** [comment]
@kpodemski it works! Thank you very much ;)

**Comment by Louis7777** [comment]
@kpodemski @andreacasali 

I am using 1.7.1.1 and assets are not loaded for child themes, not even the custom.css that is supposed to be loaded by default!

Instead, I get the parent's custom.css. If I register it in theme.yml I still don't get the child custom.css, on the contrary, I get the parent file twice!

```
parent: classic
name: mychildtheme
display_name: A Child Theme
version: 1.0.0
author:
  name: "Myself"
assets:
  # If you're using this theme as child and you want to load
  # the parent theme assets, uncomment this line.
  use_parent_assets: true
  # The following lines are showing how to load assets in your page
  # Uncomment and change value to start loading css or js files
  css:
    all:
      - id: custom-lib-style
        path: assets/css/custom.css
```

**Comment by AntoineMoues** [comment]
@Louis7777 

Comment the line 

```
use_parent_assets: true 
```

Or set it to false

```
use_parent_assets: false
```

**Comment by Louis7777** [comment]
@AntoineMoues 

But can it be a child theme without the parent's assets?

**Comment by AntoineMoues** [comment]
@Louis7777 

Yes, it can be

**Comment by Eneymotorny** [comment]
> config/themes/themename/shop1.json

**Comment by xrdm** [comment]
The issue it's not solved. I have the same problems with version 1.7.2.4 (and file in config/themes/... it's not present).

**Comment by bishamontn** [comment]
Here the same issue in 1.7.2.4 the related folder doesn't exist. Anyone has a solution?

**Comment by a-polounovsky** [comment]
Hi
Same problem for me also

**Comment by kpodemski** [comment]
Guys, check app/cache folder as the previous one is depreceated

**Comment by jclopmel** [comment]
Same happens in my project. New assets can't be loaded with the same structure. I can remove cache files and even find app/cache. No way to load js. Anyone solved the problem?

`assets:

  use_parent_assets: false
  css:
    all:
      - id: custom-lib-style
        path: assets/css/custom-lib.css
    product:
      - id: product-style
        path: assets/css/product.css
  js:
    all:
      - id: owl-carousel-lib
      path: /assets/js/custom.carousel.js
      position: head
      priority: 0
      inline: true
    cart:
      - id: cart-extra-lib
        path: assets/js/cart-lib.js`

**Comment by prcwest** [comment]
Same here, Prestashop 1.7.4.2
CSS is registered and JS not

**Comment by jclopmel** [comment]
I have realised that it works, exactly in the section you declare. I mean you must be quiet accurate with:
`cart:
- id: cart-extra-lib
path: assets/js/cart-lib.js`

**Comment by prcwest** [comment]
you are correct. it works.

**Comment by niccolomineo** [comment]
> @andreacasali it is working but you need to delete config/themes/themename/shop1.json file to reload updated .yml file in your back-office, it is fixed in 1.7.1 but not working as expected on 1.7.0.x

Thank you. This seems to still be an issue in 1.7.5.1.

**Comment by rateforx** [comment]
> 
> 
> @andreacasali it is working but you need to delete config/themes/themename/shop1.json file to reload updated .yml file in your back-office, it is fixed in 1.7.1 but not working as expected on 1.7.0.x

Still not fixed in 1.7.5.0.

**Comment by nexispl** [comment]
> > @andreacasali it is working but you need to delete config/themes/themename/shop1.json file to reload updated .yml file in your back-office, it is fixed in 1.7.1 but not working as expected on 1.7.0.x
> 
> Still not fixed in 1.7.5.0.

Not fixed in 1.7.6 too. Fortunately, deleting shop.json file works fine
